apiVersion: apps/v1
kind: Deployment
metadata:
    name: udagram-front
    labels:
        app: udagram-front
spec:
    replicas: 2
    selector:
        matchLabels:
            app: udagram-front
    template:
        metadata:
            labels:
                app: udagram-front
        spec:
            containers:
                - name: udagram-front
                  image: ofbruno/udagram-front
                  ports:
                      - containerPort: 80
