apiVersion: v1
kind: Service
metadata:
    name: udagram-front
    labels:
        run: udagram-front
spec:
    ports:
        - port: 80
          protocol: TCP
    selector:
        run: udagram-front
